project:
  type: website
  output-dir: docs

website:
  title: "Website"
  image: "website_headshot.jpeg"
  favicon: "website_headshot.jpeg"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tidy Tuesday"
        menu:
          - text: "Eclipse 4/9/24"
            href: Eclipse.html
          - text: "Chess 9/24/24"
            href: Chess.html
          - text: "Countries 11/12/24"
            href: Countries.html
          - text: "Mt. Vesuvius 5/13/25"
            href: Mt_Vesuvius.html
      - text: "400 Running Data"
        href: 400 Data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
